# Generated by Django 4.2.6 on 2023-10-14 20:07

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0004_alter_client_groups_alter_client_user_permissions'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
