# Generated by Django 4.2.6 on 2023-10-14 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_app', '0001_initial'),
        ('question_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(null=True)),
                ('favorite', models.BooleanField(default=False)),
                ('asked_in_interview', models.IntegerField(default=0)),
                ('forget', models.BooleanField(default=False)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='client_app.client')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='question_app.question')),
            ],
        ),
    ]
