# Generated by Django 4.2.6 on 2023-10-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='question',
            new_name='question_id',
        ),
    ]
