# Generated by Django 4.2.6 on 2023-10-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_app', '0003_rename_client_id_flashcard_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='answer',
            field=models.CharField(blank=True, null=True),
        ),
    ]
