# Generated by Django 4.2.6 on 2023-10-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_app', '0004_alter_flashcard_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='asked_in_interview',
            field=models.BooleanField(default=False),
        ),
    ]
